services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: seckill-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: seckill-redis
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: src/Seckill.Api/Dockerfile
    container_name: seckill-api
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      ConnectionStrings__Default: "Server=mssql,1433;Database=SeckillDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True"
      Redis__ConnectionString: "redis:6379"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "SeckillApi"
      Jwt__Audience: "SeckillClient"
    ports:
      - "${API_PORT}:8080"
    depends_on:
      mssql:
        condition: service_healthy
      redis:
        condition: service_healthy

  k6:
    image: grafana/k6:latest
    container_name: seckill-k6
    profiles: [ "loadtest" ]
    volumes:
      - ./loadtests/k6:/scripts
    working_dir: /scripts
    environment:
      BASE_URL: "http://api:8080"
      AVTIVITY_ID: "1"
    depends_on:
      api:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: src/Seckill.Worker/Dockerfile
    container_name: seckill-worker
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Default: "Server=mssql,1433;Database=SeckillDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True"
      Redis__ConnectionString: "redis:6379"
    depends_on:
      mssql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mssql-data:
  redis-data:
