<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e41018ff-808e-44b0-9ed6-fc9d7164cd8a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Seckill.Application\Seckill.Application.csproj" />
    <ProjectReference Include="..\Seckill.Infrastructure\Seckill.Infrastructure.csproj" />
  </ItemGroup>

</Project>
